-- Simple base de données commerciale (pour ORACLE Sqlplus)
-- Auteur: Didier Donsez

-- Peuplage de la table ARTICLE --


insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(400,'Ordinateur P300',15000.00,20.60);
insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(401,'Imprimante couleur',2800.00,20.60);
insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(402,'Imprimante Laser',4000.00,20.60);
insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(403,'Ordinateur P200',8000.00,20.60);
insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(404,'Modem 56K',900.00,20.60);
insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(405,'Modem 33K',600.00,20.60);
insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(406,'Scanner',1200.00,20.60);
insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(407,'Moniteur 15',2300.00,20.60);
insert into ARTICLE(RefArt,Libelle,PU,TVA) VALUES(407,'Moniteur 17',3000.00,20.60);
