-- Simple base de données commerciale (pour ORACLE Sqlplus)
-- Auteur: Didier Donsez



-- Peuplage de la table CLIENT --

insert into CLIENT(NoClient,Nom,Adresse,Ville,Reduction) VALUES(100,'Dupont','Rue de Belleville','PARIS',0.00);
insert into CLIENT(NoClient,Nom,Adresse,Ville,Reduction) VALUES(101,'Durant','Rue Lecourbe','DIJON',0.00);
insert into CLIENT(NoClient,Nom,Adresse,Ville,Reduction) VALUES(102,'Martin','Rue de Vaugirard','LILLE',0.00);
insert into CLIENT(NoClient,Nom,Adresse,Ville,Reduction) VALUES(103,'Verlande','Rue Courcelles','PARIS',0.00);
insert into CLIENT(NoClient,Nom,Adresse,Ville,Reduction) VALUES(104,'Condette','Av. République','PARIS',0.00);
insert into CLIENT(NoClient,Nom,Adresse,Ville,Reduction) VALUES(105,'Saumart','Bd. de la Villette','LILLE',0.00);
insert into CLIENT(NoClient,Nom,Adresse,Ville,Reduction) VALUES(106,'Bruant','Av. de Neuilly','BREST',10.00);
