-- Simple base de données commerciale (pour ORACLE Sqlplus)
-- Auteur: Didier Donsez



-- Peuplage de la table COMMANDE

insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(400,10,10000,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(403,1,10001,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(407,1,10001,2);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(401,1,10001,3);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(400,2,10002,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(401,1,10002,2);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(402,1,10002,3);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(400,1,10003,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(402,1,10003,2);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(403,20,10004,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(403,1,10005,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(404,15,10006,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(400,1,10007,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(402,1,10007,2);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(403,1,10008,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(401,1,10008,2);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(406,1,10009,3);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(404,1,10010,1);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(406,1,10010,2);
insert into COMMANDE(RefArt,Qte,NoFact,NoLigne) VALUES(407,1,10010,3);
