-- Simple base de données commerciale (pour ORACLE Sqlplus)
-- Auteur: Didier Donsez


-- Peuplage de la table PAIEMENT

insert into PAIEMENT(NoFact,NoPaiement,Paiement) VALUES(10000,1,180900.00);
insert into PAIEMENT(NoFact,NoPaiement,Paiement) VALUES(10002,1,20000.00);
insert into PAIEMENT(NoFact,NoPaiement,Paiement) VALUES(10002,2,24380.80);
insert into PAIEMENT(NoFact,NoPaiement,Paiement) VALUES(10003,1,22914.00);
insert into PAIEMENT(NoFact,NoPaiement,Paiement) VALUES(10004,1,192960.00);
insert into PAIEMENT(NoFact,NoPaiement,Paiement) VALUES(10010,1,1000.00);